import React from "react";
import { Box } from "@mui/material";
import Head from "next/head";
import SideNavbar from "./SideNavbar/SideNavbar";
import ProfileSettings from "../ProfileSettings/ProfileSettings";
import styles from "./Layout.module.css";

type LayoutProps = {
  title?: string;
};

const Layout: React.FC<LayoutProps> = ({
  children,
  title = "Sunday Friends",
}) => {
  return (
    <div className={styles["layout-container"]}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["container"]}>
        <SideNavbar />
        {children}
        <div className={styles["profile-settings"]}>
          <ProfileSettings />
        </div>
      </div>
    </div>
  );
};

export default Layout;
