import React from 'react';
import { Box } from '@mui/material';
import Head from 'next/head';
import SideNavbar from './SideNavbar/SideNavbar';
import styles from './Layout.module.css';

type LayoutProps = {
    title?: string;
}

const Layout: React.FC<LayoutProps> = ({
    children,
    title = 'Sunday Friends',
}) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box className={styles['container']}>
                <SideNavbar />
                {children}
            </Box>
        </div>
    );
}

export default Layout;