import Head from 'next/head';
import SideNavbar from '../components/SideNavbar/SideNavbar';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <SideNavbar />
      <Head>
        <title>Sunday Friends Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sunday Friends Admin
        </h1>
      </main>
    </div>
  )
}
